# Generated by Django 2.2 on 2021-08-12 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0005_auto_20210812_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='users_who_liked',
        ),
        migrations.RemoveField(
            model_name='message',
            name='users_who_liked',
        ),
    ]
