# Generated by Django 2.2 on 2021-08-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0007_comment_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='users_who_liked',
            field=models.ManyToManyField(related_name='comments_users_liked', to='the_wall_app.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='users_who_liked',
            field=models.ManyToManyField(related_name='messages_user_liked', to='the_wall_app.User'),
        ),
    ]
